package com.heo.dao;

import com.heo.entity.dto.ExpressAndNameDTO;
import com.heo.entity.dto.ExpressOrderNameDTO;
import com.heo.entity.dto.ExpressQueryDTO;
import com.heo.entity.dto.IncomeStatisEmailDTO;
import com.heo.entity.mapper.Express;
import com.heo.entity.mapper.ExpressExample;

import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    long countByExample(ExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int deleteByExample(ExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int insert(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int insertSelective(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    List<Express> selectByExample(ExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    Express selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Express record, @Param("example") ExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Express record, @Param("example") ExpressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Express record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table express
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int updateByPrimaryKey(Express record);


    List<ExpressAndNameDTO> selectByExpressQureyDTO(ExpressQueryDTO expressQureyDTO);


    List<ExpressOrderNameDTO> selectExpressOrderByTwoIds(Long providerId, Long neederId);


    IncomeStatisEmailDTO selectIncomeByProviderIdAndDate(Long providerId, Date date);

}