package com.heo.dao;

import com.heo.entity.mapper.ExpressInfo;
import com.heo.entity.mapper.LocationInfo;
import com.heo.entity.mapper.LocationInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    long countByExample(LocationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    int deleteByExample(LocationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    int insert(LocationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    int insertSelective(LocationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    List<LocationInfo> selectByExample(LocationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    LocationInfo selectByPrimaryKey(Byte id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") LocationInfo record, @Param("example") LocationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    int updateByExample(@Param("record") LocationInfo record, @Param("example") LocationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(LocationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location_info
     *
     * @mbg.generated Mon Sep 17 15:38:34 GMT+08:00 2018
     */
    int updateByPrimaryKey(LocationInfo record);

}