package com.heo.dao;

import com.heo.entity.mapper.LoginInformation;
import com.heo.entity.mapper.LoginInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    long countByExample(LoginInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    int deleteByExample(LoginInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Integer infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    int insert(LoginInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    int insertSelective(LoginInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    List<LoginInformation> selectByExample(LoginInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    LoginInformation selectByPrimaryKey(Integer infoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") LoginInformation record, @Param("example") LoginInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    int updateByExample(@Param("record") LoginInformation record, @Param("example") LoginInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(LoginInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_information
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    int updateByPrimaryKey(LoginInformation record);

    List<LoginInformation> selectLogininforList(LoginInformation record);
}