package com.heo.dao;

import com.heo.entity.mapper.Score;
import com.heo.entity.mapper.ScoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    long countByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int deleteByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int insert(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int insertSelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    List<Score> selectByExampleWithBLOBs(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    List<Score> selectByExample(ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    Score selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int updateByExample(@Param("record") Score record, @Param("example") ScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int updateByPrimaryKeyWithBLOBs(Score record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table score
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    int updateByPrimaryKey(Score record);
}