package com.heo.dao;

import com.heo.entity.mapper.UserOnline;
import com.heo.entity.mapper.UserOnlineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserOnlineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    long countByExample(UserOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    int deleteByExample(UserOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    int deleteByPrimaryKey(String sessionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    int insert(UserOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    int insertSelective(UserOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    List<UserOnline> selectByExample(UserOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    UserOnline selectByPrimaryKey(String sessionid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    int updateByExampleSelective(@Param("record") UserOnline record, @Param("example") UserOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    int updateByExample(@Param("record") UserOnline record, @Param("example") UserOnlineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    int updateByPrimaryKeySelective(UserOnline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_online
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    int updateByPrimaryKey(UserOnline record);

    int deleteOnlineById(String sessionId);
    int saveOnline(UserOnline userOnline);

    List<UserOnline> selectOnlineByExpired(String lastAccessTime);
}