package com.heo.entity.dto;

import com.heo.entity.mapper.Express;
import lombok.Data;

import java.math.BigDecimal;
import java.util.Date;

/**
 * @Auth justinniu
 * @Date 2018/9/29
 * @Desc
 */
@Data
public class ExpressAndNameDTO {
    private Long id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.user_id
     *
     * @mbg.generated Fri Sep 28 12:16:46 GMT+08:00 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.phone
     *
     * @mbg.generated Fri Sep 28 12:16:46 GMT+08:00 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.express_type
     *
     * @mbg.generated Fri Sep 28 12:16:46 GMT+08:00 2018
     */
    private Byte expressType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.get_code
     *
     * @mbg.generated Fri Sep 28 12:16:46 GMT+08:00 2018
     */
    private String getCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.price
     *
     * @mbg.generated Fri Sep 28 12:16:46 GMT+08:00 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.location_id
     *
     * @mbg.generated Fri Sep 28 12:16:46 GMT+08:00 2018
     */
    private Byte locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.message
     *
     * @mbg.generated Fri Sep 28 12:16:46 GMT+08:00 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.created_at
     *
     * @mbg.generated Fri Sep 28 12:16:46 GMT+08:00 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.updated_at
     *
     * @mbg.generated Fri Sep 28 12:16:46 GMT+08:00 2018
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.status
     *
     * @mbg.generated Fri Sep 28 12:16:46 GMT+08:00 2018
     */
    private Byte status;

    private String locationName;
    private String userName;
    private String nickName;
}
