package com.heo.entity.mapper;

public class ExpressKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.id
     *
     * @mbg.generated Fri Sep 21 15:47:18 GMT+08:00 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.message
     *
     * @mbg.generated Fri Sep 21 15:47:18 GMT+08:00 2018
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.id
     *
     * @return the value of express.id
     *
     * @mbg.generated Fri Sep 21 15:47:18 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.id
     *
     * @param id the value for express.id
     *
     * @mbg.generated Fri Sep 21 15:47:18 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.message
     *
     * @return the value of express.message
     *
     * @mbg.generated Fri Sep 21 15:47:18 GMT+08:00 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.message
     *
     * @param message the value for express.message
     *
     * @mbg.generated Fri Sep 21 15:47:18 GMT+08:00 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}