package com.heo.entity.mapper;

import java.math.BigDecimal;
import java.util.Date;

public class ExpressOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_order.id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_order.needer_id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    private Long neederId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_order.provider_id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    private Long providerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_order.express_id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    private Long expressId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_order.price
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_order.status
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_order.created_at
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express_order.updated_at
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_order.id
     *
     * @return the value of express_order.id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_order.id
     *
     * @param id the value for express_order.id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_order.needer_id
     *
     * @return the value of express_order.needer_id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public Long getNeederId() {
        return neederId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_order.needer_id
     *
     * @param neederId the value for express_order.needer_id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public void setNeederId(Long neederId) {
        this.neederId = neederId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_order.provider_id
     *
     * @return the value of express_order.provider_id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_order.provider_id
     *
     * @param providerId the value for express_order.provider_id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_order.express_id
     *
     * @return the value of express_order.express_id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public Long getExpressId() {
        return expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_order.express_id
     *
     * @param expressId the value for express_order.express_id
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public void setExpressId(Long expressId) {
        this.expressId = expressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_order.price
     *
     * @return the value of express_order.price
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_order.price
     *
     * @param price the value for express_order.price
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_order.status
     *
     * @return the value of express_order.status
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_order.status
     *
     * @param status the value for express_order.status
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_order.created_at
     *
     * @return the value of express_order.created_at
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_order.created_at
     *
     * @param createdAt the value for express_order.created_at
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express_order.updated_at
     *
     * @return the value of express_order.updated_at
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express_order.updated_at
     *
     * @param updatedAt the value for express_order.updated_at
     *
     * @mbg.generated Fri Sep 21 15:30:28 GMT+08:00 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}