package com.heo.entity.mapper;

import java.util.Date;

public class Express {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.id
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.user_id
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.phone
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.type
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.key
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.money
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    private Long money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.location_id
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    private Byte locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.message
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.created_at
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column express.updated_at
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.id
     *
     * @return the value of express.id
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.id
     *
     * @param id the value for express.id
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.user_id
     *
     * @return the value of express.user_id
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.user_id
     *
     * @param userId the value for express.user_id
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.phone
     *
     * @return the value of express.phone
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.phone
     *
     * @param phone the value for express.phone
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.type
     *
     * @return the value of express.type
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.type
     *
     * @param type the value for express.type
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.key
     *
     * @return the value of express.key
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.key
     *
     * @param key the value for express.key
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.money
     *
     * @return the value of express.money
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public Long getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.money
     *
     * @param money the value for express.money
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public void setMoney(Long money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.location_id
     *
     * @return the value of express.location_id
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public Byte getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.location_id
     *
     * @param locationId the value for express.location_id
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public void setLocationId(Byte locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.message
     *
     * @return the value of express.message
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.message
     *
     * @param message the value for express.message
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.created_at
     *
     * @return the value of express.created_at
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.created_at
     *
     * @param createdAt the value for express.created_at
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column express.updated_at
     *
     * @return the value of express.updated_at
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column express.updated_at
     *
     * @param updatedAt the value for express.updated_at
     *
     * @mbg.generated Sun Sep 16 09:45:50 GMT+08:00 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}