package com.heo.entity.mapper;

public class LocationInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_info.id
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    private Byte id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_info.part
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    private Byte part;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_info.name
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location_info.content
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_info.id
     *
     * @return the value of location_info.id
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_info.id
     *
     * @param id the value for location_info.id
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_info.part
     *
     * @return the value of location_info.part
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    public Byte getPart() {
        return part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_info.part
     *
     * @param part the value for location_info.part
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    public void setPart(Byte part) {
        this.part = part;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_info.name
     *
     * @return the value of location_info.name
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_info.name
     *
     * @param name the value for location_info.name
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location_info.content
     *
     * @return the value of location_info.content
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location_info.content
     *
     * @param content the value for location_info.content
     *
     * @mbg.generated Thu Sep 27 11:08:08 GMT+08:00 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    @Override
    public String toString() {
        return "LocationInfo{" +
                "id=" + id +
                ", part=" + part +
                ", name='" + name + '\'' +
                ", content='" + content + '\'' +
                '}';
    }
}