package com.heo.entity.mapper;

import java.util.Date;

public class LoginInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_information.info_id
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    private Integer infoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_information.user_name
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_information.ipaddr
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    private String ipaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_information.login_location
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    private String loginLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_information.browser
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_information.os
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    private String os;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_information.status
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_information.msg
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_information.login_time
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    private Date loginTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_information.info_id
     *
     * @return the value of login_information.info_id
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public Integer getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_information.info_id
     *
     * @param infoId the value for login_information.info_id
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public void setInfoId(Integer infoId) {
        this.infoId = infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_information.user_name
     *
     * @return the value of login_information.user_name
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_information.user_name
     *
     * @param userName the value for login_information.user_name
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_information.ipaddr
     *
     * @return the value of login_information.ipaddr
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_information.ipaddr
     *
     * @param ipaddr the value for login_information.ipaddr
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr == null ? null : ipaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_information.login_location
     *
     * @return the value of login_information.login_location
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public String getLoginLocation() {
        return loginLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_information.login_location
     *
     * @param loginLocation the value for login_information.login_location
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public void setLoginLocation(String loginLocation) {
        this.loginLocation = loginLocation == null ? null : loginLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_information.browser
     *
     * @return the value of login_information.browser
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_information.browser
     *
     * @param browser the value for login_information.browser
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_information.os
     *
     * @return the value of login_information.os
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_information.os
     *
     * @param os the value for login_information.os
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_information.status
     *
     * @return the value of login_information.status
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_information.status
     *
     * @param status the value for login_information.status
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_information.msg
     *
     * @return the value of login_information.msg
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_information.msg
     *
     * @param msg the value for login_information.msg
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_information.login_time
     *
     * @return the value of login_information.login_time
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_information.login_time
     *
     * @param loginTime the value for login_information.login_time
     *
     * @mbg.generated Wed Sep 12 15:12:59 GMT+08:00 2018
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
}