package com.heo.entity.mapper;

public class Score {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.id
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.provider_id
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    private Long providerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.needer_id
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    private Long neederId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.attitude
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    private Byte attitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.speed
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    private Byte speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column score.comment
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.id
     *
     * @return the value of score.id
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.id
     *
     * @param id the value for score.id
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.provider_id
     *
     * @return the value of score.provider_id
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public Long getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.provider_id
     *
     * @param providerId the value for score.provider_id
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public void setProviderId(Long providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.needer_id
     *
     * @return the value of score.needer_id
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public Long getNeederId() {
        return neederId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.needer_id
     *
     * @param neederId the value for score.needer_id
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public void setNeederId(Long neederId) {
        this.neederId = neederId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.attitude
     *
     * @return the value of score.attitude
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public Byte getAttitude() {
        return attitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.attitude
     *
     * @param attitude the value for score.attitude
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public void setAttitude(Byte attitude) {
        this.attitude = attitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.speed
     *
     * @return the value of score.speed
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public Byte getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.speed
     *
     * @param speed the value for score.speed
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public void setSpeed(Byte speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column score.comment
     *
     * @return the value of score.comment
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column score.comment
     *
     * @param comment the value for score.comment
     *
     * @mbg.generated Sat Nov 03 21:29:44 GMT+08:00 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}