package com.heo.entity.mapper;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pass_word
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String passWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.salt
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private Integer salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.major_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String majorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.location_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private Byte locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.type
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.alipay_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String alipayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.wechat_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String wechatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq_number
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String qqNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.picture
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.student_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.created_at
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updated_at
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.modify_by
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private Byte modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.login_ip
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.last_login
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    private Date lastLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pass_word
     *
     * @return the value of user.pass_word
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pass_word
     *
     * @param passWord the value for user.pass_word
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord == null ? null : passWord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.salt
     *
     * @return the value of user.salt
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public Integer getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.salt
     *
     * @param salt the value for user.salt
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setSalt(Integer salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.major_id
     *
     * @return the value of user.major_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getMajorId() {
        return majorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.major_id
     *
     * @param majorId the value for user.major_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setMajorId(String majorId) {
        this.majorId = majorId == null ? null : majorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.location_id
     *
     * @return the value of user.location_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public Byte getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.location_id
     *
     * @param locationId the value for user.location_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setLocationId(Byte locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.type
     *
     * @return the value of user.type
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.type
     *
     * @param type the value for user.type
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.alipay_id
     *
     * @return the value of user.alipay_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getAlipayId() {
        return alipayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.alipay_id
     *
     * @param alipayId the value for user.alipay_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setAlipayId(String alipayId) {
        this.alipayId = alipayId == null ? null : alipayId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.wechat_id
     *
     * @return the value of user.wechat_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.wechat_id
     *
     * @param wechatId the value for user.wechat_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId == null ? null : wechatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq_number
     *
     * @return the value of user.qq_number
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getQqNumber() {
        return qqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq_number
     *
     * @param qqNumber the value for user.qq_number
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setQqNumber(String qqNumber) {
        this.qqNumber = qqNumber == null ? null : qqNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.picture
     *
     * @return the value of user.picture
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.picture
     *
     * @param picture the value for user.picture
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.student_id
     *
     * @return the value of user.student_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.student_id
     *
     * @param studentId the value for user.student_id
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.created_at
     *
     * @return the value of user.created_at
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.created_at
     *
     * @param createdAt the value for user.created_at
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updated_at
     *
     * @return the value of user.updated_at
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updated_at
     *
     * @param updatedAt the value for user.updated_at
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.modify_by
     *
     * @return the value of user.modify_by
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public Byte getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.modify_by
     *
     * @param modifyBy the value for user.modify_by
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setModifyBy(Byte modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.login_ip
     *
     * @return the value of user.login_ip
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.login_ip
     *
     * @param loginIp the value for user.login_ip
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.last_login
     *
     * @return the value of user.last_login
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public Date getLastLogin() {
        return lastLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.last_login
     *
     * @param lastLogin the value for user.last_login
     *
     * @mbg.generated Mon Sep 17 15:11:23 GMT+08:00 2018
     */
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
}