package com.heo.entity.mapper;

import com.heo.common.utils.AddressUtils;
import com.heo.dao.OnlineSession;

import java.util.Date;

public class UserOnline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.sessionId
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    private String sessionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.user_name
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.ipaddr
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    private String ipaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.login_location
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    private String loginLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.browser
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    private String browser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.os
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    private String os;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.status
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.start_timestsamp
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    private Date startTimestsamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.last_access_time
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    private Date lastAccessTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_online.expire_time
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    private Integer expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.sessionId
     *
     * @return the value of user_online.sessionId
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */

    private OnlineSession onlineSession;

    public OnlineSession getOnlineSession() {
        return onlineSession;
    }

    public void setOnlineSession(OnlineSession onlineSession) {
        this.onlineSession = onlineSession;
    }

    public String getSessionid() {
        return sessionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.sessionId
     *
     * @param sessionid the value for user_online.sessionId
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public void setSessionid(String sessionid) {
        this.sessionid = sessionid == null ? null : sessionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.user_name
     *
     * @return the value of user_online.user_name
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.user_name
     *
     * @param userName the value for user_online.user_name
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.ipaddr
     *
     * @return the value of user_online.ipaddr
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public String getIpaddr() {
        return ipaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.ipaddr
     *
     * @param ipaddr the value for user_online.ipaddr
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public void setIpaddr(String ipaddr) {
        this.ipaddr = ipaddr == null ? null : ipaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.login_location
     *
     * @return the value of user_online.login_location
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public String getLoginLocation() {
        return loginLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.login_location
     *
     * @param loginLocation the value for user_online.login_location
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public void setLoginLocation(String loginLocation) {
        this.loginLocation = loginLocation == null ? null : loginLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.browser
     *
     * @return the value of user_online.browser
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.browser
     *
     * @param browser the value for user_online.browser
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.os
     *
     * @return the value of user_online.os
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.os
     *
     * @param os the value for user_online.os
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.status
     *
     * @return the value of user_online.status
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.status
     *
     * @param status the value for user_online.status
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.start_timestsamp
     *
     * @return the value of user_online.start_timestsamp
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public Date getStartTimestsamp() {
        return startTimestsamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.start_timestsamp
     *
     * @param startTimestsamp the value for user_online.start_timestsamp
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public void setStartTimestsamp(Date startTimestsamp) {
        this.startTimestsamp = startTimestsamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.last_access_time
     *
     * @return the value of user_online.last_access_time
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public Date getLastAccessTime() {
        return lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.last_access_time
     *
     * @param lastAccessTime the value for user_online.last_access_time
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public void setLastAccessTime(Date lastAccessTime) {
        this.lastAccessTime = lastAccessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_online.expire_time
     *
     * @return the value of user_online.expire_time
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public int getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_online.expire_time
     *
     * @param expireTime the value for user_online.expire_time
     *
     * @mbg.generated Wed Sep 12 10:51:23 GMT+08:00 2018
     */
    public void setExpireTime(Integer expireTime) {
        this.expireTime = expireTime;
    }

    public static final UserOnline fromOnlineSession(OnlineSession session)
    {
        UserOnline online = new UserOnline();
        online.setSessionid(String.valueOf(session.getId()));
        online.setUserName(session.getUserName());
        online.setStartTimestsamp(session.getStartTimestamp());
        online.setLastAccessTime(session.getLastAccessTime());
        online.setExpireTime((int) session.getTimeout());
        online.setIpaddr(session.getHost());
        online.setLoginLocation(AddressUtils.getRealAddressByIP(session.getHost()));
        online.setBrowser(session.getBrowser());
        online.setOs(session.getOs());
        online.setStatus(session.getStatus().getInfo());
        online.setOnlineSession(session);
        return online;
    }
}